name: Deploy 

on:
  push:
    branches: [Master]
  pull_request:
    branches: [Master]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - run: pnpm install
    - run: pnpm run lint
    - run: pnpm run type-check
    - run: pnpm run build